### ISSUE TITLE
No suitable database adapter found! pyexcel/Flask-Excel

### ISSUE THREAD

**Issue by AnastasiaLd** [pyexcel-webwares/Flask-Excel#27]
We have a file, we have created the tables with the same column names and everything seems to be fine. We get the error: `No suitable database adapter found!` When we try to upload any excel file.

When we try to upload any excel file. We have tried this with a basic excel file mimicing the same columns in case there was an issue with the originating file. This has not resolved the issue. We have also created a new file with the same column names and entered some basic data and this still returns the same error.

**Comment by chfw** [comment]
It means you have more sheets in your excel file than the number of tables to be written into.

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel-io/issues/42

**Comment by AnastasiaLd** [comment]
Thank you. The problem is that i have one excel file with one single sheet (is a log file so i won't always be able to identify the sheet name). What i would like, and i don't know if this extensions supports this, is to write certain columns of my file into different tables of my database (col 1, col 2, col 6 into table a / col 8 col 3 into table b...). How would i do this?
Again thank you so much for your help.

**Comment by chfw** [comment]
I think you should [get a sheet instance](http://flask-excel.readthedocs.io/en/latest/#flask_excel.ExcelRequest.get_sheet) from your upload, and then use [sheet.Column](https://github.com/pyexcel/pyexcel/blob/master/pyexcel/internal/sheets/column.py#L46) to choose your columns and then [sheet.save_to_database](http://pyexcel.readthedocs.io/en/latest/generated/pyexcel.Sheet.save_to_database.html#pyexcel.Sheet.save_to_database).

**Comment by AnastasiaLd** [comment]
Thanks but are the initializers required? I am still having problems between my file and my models. 
Basically i have an excel/csv file like this (only one sheet/ sheet name changes so i can't indicate it):

Logs.csv
name | phone_num | account_code

Then in my models i have:

```
class Logs(db.Model):
    __tablename__ = 'Logs'
    id = db.Column(db.Integer, primary_key = True, unique = True)
    name = db.Column(db.String, nullable = False)
    phone_num = db.Column(db.Integer, nullable = False)
    account_code = db.Column(db.VARCHAR(120), nullable = True)

#My table has no foreign keys or dependencies from other tables

    def __init__(**kwargs):
        super(Rates, self).__init__(**kwargs)
```

This is in my views.py file:
```
@upload.route('/upload', methods = ['GET', 'POST'])
def upload_new_cdr():
	form = UploadForm()
	if form.validate_on_submit():

		#Get a sheet instance
		uploaded_file = request.get_sheet(field_name = 'upload')

		#Select columns by name
		uploaded_file.name_columns_by_row(0)
		uploaded_file.column.select(['name' , 'phone_num', 'account_code',])
                #This works fine an it prints
                name | phone_num | account_code
                Ana     5567584         112
                Lana   995588            122
                Diana  676768            130
		print uploaded_file

		#Save to database
                #This is where it fails (i have both tried to put and not the initializers)
		uploaded_file.save_to_database(session = db.session, table = Logs)
		return 'SAVED!'

	return render_template('upload/upload.html', form=form)
```

I get an argment error from pyexcel_io and i am not sure what argument am i missing or what's happening:

TypeError: __init__() takes exactly 0 arguments (1 given)


Erro line:
```
        if self._native_sheet.row_initializer:

            # allow initinalizer to return None

            # if skipping is needed

            obj = self._native_sheet.row_initializer(row)

        if obj is None:

            obj = self._native_sheet.table() #<--- ERROR -->

            for name in self._native_sheet.column_names:

                if self._native_sheet.column_name_mapping_dict is not None:

                    key = self._native_sheet.column_name_mapping_dict[name]

                else:

                    key = name
```

Really sorry for this many questions( and for the begginer mistakes)

**Comment by chfw** [comment]
So, what's the error you got?

**Comment by AnastasiaLd** [comment]
TypeError: __init__() takes exactly 0 arguments (1 given)

2017-10-04 12:56 GMT+01:00 jaska <notifications@github.com>:

**Comment by chfw** [comment]
And can you initialize a Logs instance elsewhere (I means outside pyexcel's context)? and how do you initialized one?

**Comment by AnastasiaLd** [comment]
When i indicate an initializer i use this:
```
		def logs_init_func(row):
			logs = Caller(row['name'], row['phone_num'],
			, row['account_code'])
			return caller

		uploaded_file.save_to_database(
            session=db.session,
            table=Logs,
            initializer=caller_init_func)
```
Not sure however if the initializing functions are for the tables or for the sheet?
By doing that i still get an argument error, same as if i don't use the initializer.

**Comment by chfw** [comment]
For the table

**Comment by AnastasiaLd** [comment]
Thank you, however why am i getting an argument error? I don't understand what i am doing wrong

**Comment by chfw** [comment]
Could you please post me all the code about `class Logs`? You can email me the code to wangc_2011@hotmail.com if you want some privacy around your code. I don't think it is rocket science.

**Comment by LukasSliacky** [comment]
Hi chfw, any news? I use version 0.0.7 and i have same problem :/

**Comment by chfw** [comment]
@LukasSliacky , the problem was resolved offline. Can you briefly describe your problem? How did you get this database adapter not found?

**Comment by starYellow966** [comment]
when i modify my sheet'name to my class name, it works!!

**Comment by juso** [comment]
Sorry for writing in already close issue, but I think it's the best place since I face the same issue while running flask-excel examples (database_example.py and database_example_formatted.py). Let me know if it's better to open a new issue on this matter

**Comment by chfw** [comment]
Please create a new issue.
