### ISSUE TITLE
View function did not return a response

### ISSUE THREAD

**Issue by jsooter** [pyexcel-webwares/Flask-Excel#29]
With a simple example I get an error (View function did not return a response):

return flask_excel.make_response_from_array([[1,2], [3, 4]], "csv", file_name="example")

Python 3.5.3

**Comment by chfw** [comment]
Hi, there was a minor change in the api since 0.0.7. The change is:

> the intialization method has been modified. please call init_excel(app) before you do anything else. This change was made in order to apply for approved flask extension status. And by doing this change, it will support multiple Flask apps and only the app that was initialized with init_excel gets Flask-Excel and other apps in your BIG app won't get affected.

Here is the setup instructions: http://flask-excel.readthedocs.io/en/latest/#setup
