### ISSUE TITLE
the response of make_response_from_array(array,file_type,file_name) is None! Different project ,same array, but different response.One is None. One is <Response 87649 bytes [200 OK]>.WHY?

### ISSUE THREAD

**Issue by hannah168** [pyexcel-webwares/Flask-Excel#32]
The response of make_response_from_array(array,file_type,file_name) is None! 
Different project ,same array, same logic, but different response. One is None. One is <Response 87649 bytes [200 OK]>.
Could you please tell what happened ? and  what's wrong with my project?
I don't know how to describe this question!!! 
Hope you can see it. Thanks you very much!!!

**Comment by hannah168** [comment]
There are some messages for this question.
DEBUG:pyexcel.internal.source_plugin.SourcePluginManager:load me now:sheet-read
DEBUG:pyexcel.internal.source_plugin.SourcePluginManager:import pyexcel.plugins.sources.pydata.arraysource.ArraySource
DEBUG:pyexcel.internal.source_plugin.SourcePluginManager:load me now:sheet-write
DEBUG:pyexcel.internal.source_plugin.SourcePluginManager:import pyexcel.plugins.sources.output_to_memory.WriteSheetToMemory
DEBUG:pyexcel.internal.plugins.IOPluginManager:import pyexcel.plugins.renderers.excel.ExcelRenderer
DEBUG:pyexcel.internal.plugins.IOPluginManager:load <class 'pyexcel.plugins.renderers.excel.ExcelRenderer'> now for 'xlsx'
DEBUG:pyexcel_io.plugins.IOManager:import pyexcel_xlsx.xlsxw.XLSXWriter
DEBUG:pyexcel_io.plugins.IOManager:load <class 'pyexcel_xlsx.xlsxw.XLSXWriter'> now for 'xlsx'
Please help me! Thank you!!

**Comment by chfw** [comment]
Sorry for the trouble.

Please place a break point into make_repsonse of flask_excel and run your test scenario.

**Comment by hannah168** [comment]
Dear friend:
In the _init_ file of pyexcel_webio , there are some functions. Like this:

 def dummy_func(content, content_type=None, status=200, file_name=None):
    return None

__excel_response_func__ = dummy_func

def _make_response(content, file_type,
                   status=200, file_name=None):
    if hasattr(content, "read"):
        content = content.read()
    if file_name:
        if not file_name.endswith(file_type):
            file_name = "%s.%s" % (file_name, file_type)
    return __excel_response_func__(
        content,
        content_type=FILE_TYPE_MIME_TABLE[file_type],
        status=status, file_name=file_name)

when I use the function of _make_response(), it will call the function of __excel_response_func__(). But this function is the same as dummy_func(). So my project got the response of None.  But another one didn't call the dummy_func(). So it got the right response. 
Could you please tell me when and what conditions to call this function dummy_func()?  There are something wrong about my data? or others?
I am looking forward to your reply! Thank you very much!!

**Comment by hannah168** [comment]
Hello Friend.
The problem has been solved. 
I am sorry to bother you.
And thanks for your replying!
Have a good day!
