### ISSUE TITLE
ImportError: No module named flask_excel

### ISSUE THREAD

**Issue by AHerreraDev** [pyexcel-webwares/Flask-Excel#36]
Hey there. Here is what I have:

main.py
import flask_excel

requirements.txt
Flask-excel

pip list
Flask-Excel              0.0.7

And I get ImportError... I have uninstalled, re-installed, leave the virtual env, re-join the virtual env. Nothing seems to work...

**Comment by chfw** [comment]
Frustrating, isn't it?

Please check if you have it installed globally by accident or not. When I create virtualenv, I choose to put --no-site-packages.

**Comment by AHerreraDev** [comment]
Thank you!
