### ISSUE TITLE
Only in wsgi environment, occur response type error 

### ISSUE THREAD

**Issue by maifire** [pyexcel-webwares/Flask-Excel#37]
Hi,

**[My environment]**
Windows 10
Python 3.6
IIS 7.5 or Apache 2.4.37 (I checked both environment with fastcgi, mod_wsgi)

**[Condition]**
Below code run well in flask cmd mode(ex> python excel_test.py)
http://localhost:5000/export
But when run in IIS or Apache meet TypeError(maybe 'None' Returned).

**[Sample Code]**
@app.route("/export", methods=['GET'])
def export_records():
    return excel.make_response_from_array([[1, 2], [3, 4]], "xlsx", file_name="export_data")

**[Error]**
Error occurred:
Traceback (most recent call last):
  File "c:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\python\lib\site-packages\flask\app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "c:\python\lib\site-packages\flask\app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.

**[Workaround]**
I had googling and find this code well worked in IIS, Apache.
 
@app.route("/export2", methods=['GET'])
def export_records2():
    csvlist = [[1, 2], [3, 4]]
    df = pd.DataFrame(csvlist, columns=["Team", "Player"])
    
    print(df)
    
    output = io.BytesIO()
    writer = pd.ExcelWriter(output)
    df.to_excel(writer, 'Tab1')
    writer.save()
    
    resp = make_response(output.getvalue())
    resp.headers['Content-Disposition'] = 'attachment; filename=output.xlsx'
    resp.headers["Content-type"] = "text/csv"
    return resp

Thanks for your help

**Comment by chfw** [comment]
for flask-excel to work well, the following line should have been called. When wsgi, the block after `__name__ == '__main__'` is normally ignored. 

https://github.com/pyexcel-webwares/Flask-Excel/blob/master/examples/tiny_example.py#L46

**Comment by maifire** [comment]
Thanks for your help chfw.
The code below worked well:)

@app.route("/export", methods=['GET'])
def export_records():
    excel.init_excel(app)
    return excel.make_response_from_array([[1, 2], [3, 4]], "csv",
                                          file_name="export_data")

**Comment by chfw** [comment]
It would better to place it in your wsgi run function.
