### ISSUE TITLE
How can I make the query result collection incrementally join the file stream of the flask-excel interface

### ISSUE THREAD

**Issue by smartAndgoodMark** [pyexcel-webwares/Flask-Excel#38]
How can I make the query result collection incrementally join the file stream of the flask-excel interface or other methods to solve the error situation that the query result is too large and the memory is insufficient?

When I query Mysql for a number of hundreds of thousands, tens of columns of data by flask-sqlalchemy, I will be in the query.all () due to insufficient memory, the process is terminated

`code 137 (interrupted by signal 9 sigkill)`

I find some ways:
https://stackoverflow.com/questions/1145905/sqlalchemy-scan-huge-tables-using-orm
https://github.com/sqlalchemy/sqlalchemy/wiki/WindowedRangeQuery
There are some methods that can be tried, but I have not found a function that flask-excel can handle incrementally.

If I don’t describe enough, I can add details.

**Comment by chfw** [comment]
I think with sqlalchemy you can do pagination with your query. however, flask-excel may help you do this incrementally if you use pyexcel.Sheet, which provides very limited function for concatenation: 

```
>>> from pyexcel import Sheet
>>> s1=Sheet([[1]])
>>> s2=Sheet([[2]])
>>> s1.row += s2
>>> s1
pyexcel sheet:
+---+
| 1 |
+---+
| 2 |
+---+

```

But you are still bounded by the memory limit. And above solution may consume more memory than you do currently.

I would suggest working around this problem.

**Comment by smartAndgoodMark** [comment]
@chfw  Thank you for your reply, I have reluctantly solved this problem, but forgot to update my solution here. I finally did not use flask-excel, although it is convenient, but also abandoned sqlalchemy, because the use of the results will be list type, will exceed the memory limit, directly using pymysql + CSV UnicodeWriter (writerows), I found it was a wrong need about sqlachemy
