### ISSUE TITLE
Where does Flask-Excel save uploaded file?

### ISSUE THREAD

**Issue by alik472** [pyexcel-webwares/Flask-Excel#40]
Usually when you upload a file it gets saved to  memory in your server. 

-Where does Flask-Excel save files? 
-How does the file is deleted after saving?
-If the file is saved in memory will this affect the memory or speed of my Flask application or web server?

**Comment by chfw** [comment]
Very good questions. Short answers:

Small files are stored by Flask in memory and Big files are stored in temp directories. Yes, in-memory small file will speed up data execution.

More information can be found on [Flask documentation](http://flask.pocoo.org/docs/1.0/patterns/fileuploads/#improving-uploads)

What does Flask-Excel do more than pyexcel? It exposes pyexcel signature functions via Flask.request object.

**Comment by alik472** [comment]
thx
