### ISSUE TITLE
How can I used make_response_from_query_sets() where column_names change to new name

### ISSUE THREAD

**Issue by zengaorong** [pyexcel-webwares/Flask-Excel#42]
column_names = ['chapter_id','story_id', 'story_url']
    return excel.make_response_from_query_sets(story_list, column_names, file_name='test',file_type='xlsx')

   I want  used column_names = ['chapterid','storyid', 'storyurl'] replace
  and my query is outerjoin ,so How I can make it to excel

**Comment by chfw** [comment]
Your code looks OK. What’s the problem?

**Comment by zengaorong** [comment]
column_names must be same as query field value

column_names = ['chapter_id','story_id', 'story_url'] is ok
column_names = ['chapterid','storyid', 'storyurl']  is wrong
and I sometime must replace the value

**Comment by zengaorong** [comment]
> 
> 
> Your code looks OK. What’s the problem?

column_names must be same as query field value

column_names = ['chapter_id','story_id', 'story_url'] is ok
column_names = ['chapterid','storyid', 'storyurl'] is wrong
and I sometime must replace the value

**Comment by zengaorong** [comment]
Thanks I solved my problem,like
    story_list = db.session.query(Story.story_id.label('id'),Story.story_url.label('url')).all()
    column_names = ['id', 'url']
    return excel.make_response_from_query_sets(story_list, column_names, file_name='test',file_type='xlsx')
