### ISSUE TITLE
 Sheet: Category does not match any given tables.Please be aware of case sensitivity.

### ISSUE THREAD

**Issue by Rorshachk** [pyexcel-webwares/Flask-Excel#43]
**It is a question.**
It's the example from [docs]( https://pythonhosted.org/Flask-Excel/#flask_excel.ExcelRequest.save_book_to_database. ) I copy the code and download the sample-data. 
It works but when I rename the sheet in the sample file, like changing `category` into `Category`, It complains like this.

> Sheet: Category does not match any given tables.Please be aware of case sensitivity.

And I check the code and manual carefully and still don't know how this "match" works. Without understanding this I can't use `save_book_to_database`. Could you explain how it works?

Thanks, and sorry for my poor English.

**Comment by chfw** [comment]
flask-sqlalchemy also put ORM table name into lower case. So in python code, you see Category but inside the database, it is 'category'.

**Comment by chfw** [comment]
> and sorry for my poor English.

Hey, you are lying. Your English is very good!

**Comment by Rorshachk** [comment]
Thanks for answering!
You mean that the because flask-sqlalchemy will automatically put capital letter into a lower case, so the name of sheet shouldn't contain any capital letter?
But I just want to know how this "match" works, to be more specifically, if I change the sheet's name, how to modify the sample code to make it work?

> Hey, you are lying. Your English is very good!

Thanks for your encouragement XD. I learn English hard in recent days.
