### ISSUE TITLE
Interoperability with uWSGI?

### ISSUE THREAD

**Issue by Jrokisky** [pyexcel-webwares/Flask-Excel#51]
I'm filing this issue to see if others have successfully used this package with uWSGI as I ran into some issues using this package with uWSGI. Specifically, `excel.make_response_from_array(....)` would return None. Responses were fine when using the default flask development server. 

It's entirely possible that this is due to some server configuration issues on my end. Sadly I didn't have much time to look into the issue as the associated feature development is on a deadline and since flask excel was just exporting a csv, I removed the package entirely and went with a raw python implementation.

**Comment by chfw** [comment]
it needs this initialisation function:

https://github.com/pyexcel-webwares/Flask-Excel/blob/master/flask_excel/__init__.py#L68

**Comment by Jrokisky** [comment]
Hi @chfw,

I was running the initialization function in my main call as follows:
```
if __name__ == '__main__':
    excel.init_excel(app)
    app.run(debug=False, use_debugger=False, host='127.0.0.1')
````

**Comment by chfw** [comment]
here is an example using raw pyexcel instead of Flask-Excel nor custom implementation: http://docs.pyexcel.org/en/latest/webdev.html

**Comment by Jrokisky** [comment]
@chfw Thank you!

**Comment by chfw** [comment]
```
if __name__ == '__main__':
    excel.init_excel(app)
    app.run(debug=False, use_debugger=False, host='127.0.0.1')
```

above is what you run as standalone server.

for your uwsgi app, what's your entry point?

I suspect 'None' came from this dummy function: https://github.com/pyexcel-webwares/pyexcel-webio/blob/master/pyexcel_webio/__init__.py#L307

So I think the initialization code were not present in your uwsgi app entry code.

**Comment by Jrokisky** [comment]
uWSGI ini:
```
[uwsgi]
wsgi-file = run.py
callable = app
```

run.py:
```
from project import app
import flask_excel as excel

if __name__ == '__main__':
    excel.init_excel(app)
    app.run(debug=False, use_debugger=False, host='127.0.0.1')
```

The `app` item is created in project's __init__.

> So I think the initialization code were not present in your uwsgi app entry code.

This sounds like the issue. Any recommendation for the best place to initialize?

**Comment by chfw** [comment]
Simply move line 5 outside, would make it work in both scenarios.
```
from project import app
import flask_excel as excel

excel.init_excel(app)

if __name__ == '__main__':    
    app.run(debug=False, use_debugger=False, host='127.0.0.1')
```

As to the best place, you may consider application factory: https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/ . I would imagine, you will have other configurations before the app runs.

**Comment by Jrokisky** [comment]
@chfw Thank you!
