### ISSUE TITLE
How to change the sheet name when using make_response() (or its variants)

### ISSUE THREAD

**Issue by varunsampat30** [pyexcel-webwares/Flask-Excel#52]
When using the '.xls' or '.xlsx' format, the sheet generated has a default name of 'pyexcel_sheet1'. Is there any way this can be changed?

**Comment by chfw** [comment]
except the response that gives book(more than one sheet), you can use a keyword based parameter: 'dest_sheet_name='.

underneath its implementation, it is a [save_as](http://docs.pyexcel.org/en/latest/generated/pyexcel.save_as.html#pyexcel.save_as) function from pyexcel.

**Comment by chfw** [comment]
database_example_formatted.py:

```
@app.route("/custom_export", methods=['GET'])
def docustomexport():
    query_sets = Category.query.filter_by(id=1).all()
    column_names = ['id', 'name']
    return excel.make_response_from_query_sets(query_sets, column_names, "xls", dest_sheet_name='helloworld')


```
