### ISSUE TITLE
Multiple Sheet using Flask Excel

### ISSUE THREAD

**Issue by varunsampat30** [pyexcel-webwares/Flask-Excel#53]
I was wondering what the best way is for creating a multiple sheet Excel book. I have data that is being generated live (nothing from SQL). 

My idea was to create a pyexcel_instance, use 'make_response()'. However, I was slightly confused with the best way to use PyExcel. Should I save my Pyexcel book when I make one? If so, would I have to delete the saved object to avoid memory leaks?

**Comment by chfw** [comment]
if you want to audit the dynamic response, you can choose to store pyexcel book in your server. 

in general, the memory used in a Flask handler will be disposed automatically. if you want to make sure it happens, there is no harm to do pre-emptive deletion. at the moment, with pyexcel-xlsx on large records, [the memory usage](https://github.com/pyexcel/pyexcel/issues/198) becomes a problem.
